language: node_js
node_js:
  - latest

services:
  - docker

before_script:
  - echo "check run"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed demyana/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user demyana/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend demyana/udagram-frontend:v1
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy demyana/reverseproxy:v1

after_success:
  - echo "$DOCKERPASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push demyana/udagram-api-feed:v1
  - docker push demyana/udagram-api-user:v1
  - docker push demyana/udagram-frontend:v1
  - docker push demyana/reverseproxy:v1